version: '3.6'

services:
  jaeger:
    env_file: ".env"
    ports:
      - ${JAEGER_COLLECTER_PORT}:6831/udp
      - ${JAEGER_OTEL_PORT}:4317
      - ${JAEGER_HTTP_PORT}:16686
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    image: jaegertracing/all-in-one:latest

  # minecraft: