version: '3.6'

services:
  jaeger:
    env_file: ".env"
    ports:
      - ${JAEGER_COLLECTER_PORT}:6831/udp
      - ${JAEGER_OTEL_PORT}:4317
      - ${JAEGER_HTTP_PORT}:16686
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    image: jaegertracing/all-in-one:latest

  minecraft:
    env_file: ".env"
    image: itzg/minecraft-server
    ports:
      - "${MINECRAFT_GAME_PORT}:25565"
      - "${MINECRAFT_RCON_PORT}:25575"
    environment:
      EULA: "TRUE"
      TYPE: NEOFORGE
      VERSION: "1.20.1"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./run/data:/data
      - ./build/libs:/data/mods